// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace reverseengineexample.Models;

[Table("stud")]
public partial class Stud
{
    [Key]
    [Column("sid")]
    public int Sid { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("age")]
    public int Age { get; set; }

    [Column("marks")]
    public double Marks { get; set; }
}